### ISSUE TITLE
Support for TS's JSXFactory

### ISSUE THREAD

**Issue by JSanchezIO** [Brooooooklyn/swc-node#137]
**Problem**
I intended to leverage `@swc-node/jest` with Preact and `@testing-library/preact`. To support Preact with TS, I had to add `"jsxFactory": "h"` to my `tsconfig.json` or `/** @jsx h **/` at the top of every Preact component file. The former allows me to configure the entire project once. However, I noticed with this library I'm not able to leverage the power of that TS configuration setting.

**Solution**
Add support for the TS configuration property `jsxFactory`

**Comment by Brooooooklyn** [comment]
[swc supported jsx pragma in 1.2.23](https://swc.rs/blog/2020/09/08/swc-1.2.23)

Check the version of `@swc/core` your installed and ensure it's greater than 1.2.23

**Comment by JSanchezIO** [comment]
I think there may be some miscommunication. My source code compiles fine, but my tests that use `@swc-node/jest` don't. My source code compiles with me only setting `"jsxFactory": "h"` in my `tsconfig.json`. I'd hope that `@swc-node/jest` would respect the same configuration but it doesn't. For my tests, I have to add `/** @jsx h **/` at the top of each file which works but I would rather have `@swc-node/jest` use my `"jsxFactory"` setting in my `tsconfig.json`.

**Comment by Brooooooklyn** [comment]
Thanks for your bug report, feel free to reopen it if still had problem.
