### ISSUE TITLE
Add getCacheKey to jest transformer

### ISSUE THREAD

**Issue by FabianSellmann** [Brooooooklyn/swc-node#155]
The transformer would be even faster, if it would not need to rerun every file transformation on each test run. I guess we just need to add something like 
```js
  getCacheKey() {
    return crypto
      .createHash('md5')
      .update(fs.readFileSync(__filename))
      .digest('hex');
  },
```
to the transform's exports.

**Comment by Brooooooklyn** [comment]
I've considered this before, but I need to run some benchmark suites to ensue `crypto.createHash('md5').update(fs.readFileSync(__filename)).digest('hex')` is faster than `swc.transform`.
