### ISSUE TITLE
Cannot import const enums

### ISSUE THREAD

**Issue by moltar** [Brooooooklyn/swc-node#24]
See https://github.com/cloudevents/sdk-javascript/issues/323

This is the code: https://github.com/cloudevents/sdk-javascript/blob/73f0becc2b8e4f10ae40e23b77e4161d9b5ff611/src/event/cloudevent.ts#L19-L22

It works with `ts-jest`, does not work with `@swc-node/jest@0.1.19`.

**Comment by Brooooooklyn** [comment]
see https://github.com/swc-project/swc/issues/940

**Comment by moltar** [comment]
Thanks, will close this then in favor of the issue linked.
