### ISSUE TITLE
Difficult to get decorators to work

### ISSUE THREAD

**Issue by Hless** [Brooooooklyn/swc-node#465]
In our TypeScript + React Native project I'm trying to switch our jest tests to swc. It's working great for the part of my codebase that does not use mobx, however, as soon as the transformer comes accross mobx decorators (observer, observable, action etc) the following error is thrown:

```
 TypeError: decorator is not a function

      20 |   }
      21 |
    > 22 |   @observable
         |                ^
      23 |   public width = 0;
      24 |
      25 |   @observable

      at src/styles/dimension-store.tsx:22:16
          at Array.reduce (<anonymous>)
      at _applyDecoratedDescriptor (src/styles/dimension-store.tsx:21:41)
      at Object.<anonymous> (src/styles/dimension-store.tsx:134:258)
      at Object.<anonymous> (src/styles/style-constants.base.ts:3:51)TypeError: decorator is not a function
```

I tried to patch it by including `reflect-metadata` or `core-js` in my test setups, it does remove the error but it causes mobx to fail (properties that are decorated are no longer initialized). Can't seem to figure out what the problem is.

I have the following jest config:
```
transform: {
    "^.+\\.tsx?$": [
      "@swc-node/jest",
      // configuration
      {
        esModuleInterop: true,
        dynamicImport: true,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
      },
    ],
    "^.+\\.js$": `${packageRoot}/node_modules/react-native/jest/preprocessor.js`,
  }
  ```

**Comment by Brooooooklyn** [comment]
See https://mobx.js.org/enabling-decorators.html#typescript , use `Mobx` decorator needs the `useDefineForClassFields: true` with `experimentalDecorators: true` which is not supported by swc.
/cc @kdy1

**Comment by Hless** [comment]
That makes sense, perhaps time to look into upgrading mobx at last (they dropped the decorator syntax in v6)

**Comment by Hless** [comment]
@Brooooooklyn  Nevermind, I just did some research, I'm not using the `useDefineForClassFields` at all in my TSConfig, because I'm still on mobx 5. So I suppose it's a different issue after all?

**Comment by Hless** [comment]
Fixed by importing `reflect-metadata` in my test setup.
