### ISSUE TITLE
TypeError: Cannot set property 'filename' of null

### ISSUE THREAD

**Issue by moltar** [Brooooooklyn/swc-node#5]
Getting the following error for every test file when running all jest tests:

```
TypeError: Cannot set property 'filename' of null
```

But if I run a single jest test, by passing in a filename, it runs just fine.

Any ideas?

**Comment by Brooooooklyn** [comment]
Upgrade to latest version: `yarn add @swc-node/jest@0.1.12` and try again

**Comment by moltar** [comment]
Thanks. That fixed the reported issue.
