### ISSUE TITLE
How to change sws config for Jest runner?

### ISSUE THREAD

**Issue by moltar** [Brooooooklyn/swc-node#51]
I want to set `dynamicImport` to `true`.

I tried using the `.swcrc` file in the root, but that did not work.

Any clues?

Thanks!

**Comment by Brooooooklyn** [comment]
```js
// jest.config.js
{
  transform: { '^.+\\.(t|j)sx?$': ['@swc-node/jest', { dynamicImport: true }] }
}
```
All options: https://github.com/Brooooooklyn/swc-node/blob/master/packages/core/index.ts#L6

**Comment by moltar** [comment]
Thanks! :)

**Comment by moltar** [comment]
Hm, interestingly I am getting the following error:

> A dynamic import callback was not specified

While it works fine with `ts-jest`.

**Comment by Brooooooklyn** [comment]
Could you please provide a minimal example which caused the compile error?
