### ISSUE TITLE
Minimal example which causes: A dynamic import callback was not specified

### ISSUE THREAD

**Issue by moltar** [Brooooooklyn/swc-node#54]
Could you please provide a minimal example which caused the compile error?

_Originally posted by @Brooooooklyn in https://github.com/Brooooooklyn/swc-node/issues/51#issuecomment-684613072_

Repro: https://github.com/moltar/swc-node-jest-exp

**Comment by Brooooooklyn** [comment]
Related: https://github.com/swc-project/swc/issues/1018

**Comment by Brooooooklyn** [comment]
Close via https://github.com/Brooooooklyn/swc-node/commit/4bbe7f4a86ca5b0fe005415162c156cf4c0a8c4d
