### ISSUE TITLE
Does this also minify?

### ISSUE THREAD

**Issue by floydjones1** [Brooooooklyn/swc-node#572]
What makes this so much faster than the native @swc/core?
And does is also provide minification?

**Comment by Brooooooklyn** [comment]
> Does this also minify

minify feature in swc is unstable now, so I will implement it in next few weeks after it become more stable.

> What makes this so much faster than the native @swc/core?

It used to be faster than `@swc/core`, but now it's exactly the same performance with `@swc/core` after https://github.com/swc-project/swc/issues/852 merged.

The major differences between `@swc-node/core` and `@swc/core` is `@swc-node/core` provide `tsconfig.json` compatible configuration, while `@swc/core` accept raw swc style config.

**Comment by floydjones1** [comment]
Ahh great, thanks for the quick reply and contributing to swc! 🎩
