### ISSUE TITLE
Q: how to go in debug mode

### ISSUE THREAD

**Issue by AlexandreDecollas** [Brooooooklyn/swc-node#612]
Hi, 

I tried several things, but nothing worked, so I come directly ask the question : 

I want to be able to debug my jest tests, so put a break point in my IDE, and be able to stop on it, like with ts-jest. but with swc, it fails. I supposed that the source-maps were missing, but event with the option 
```json
{
  "sourceMaps": true
}
```
in my .swcrc file it fails. Does someone has the same issue or have a solution please?

**Comment by Brooooooklyn** [comment]
See https://github.com/Brooooooklyn/swc-node/tree/master/packages/jest#configuration

```js
// jest.config.js
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc-node/jest',

      // configuration
      {
        sourcemap: true
      },
    ],
  },
}
```

**Comment by AlexandreDecollas** [comment]
Thank you for your answer :) I tried this option, but it does not work. My jest.config.js is : 
```js
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc-node/jest',
      {
        experimentalDecorators: true,
        sourcemap: true,
      },
    ],
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './src',
  testRegex: '.spec.(t|j)s$',
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
```

Should I run jest with some specific option to enable debugging? Else, where can I check the sourcemaps are effectively generated?

**Comment by AlexandreDecollas** [comment]
I downloaded the swc-node project, and succedded to stop at a break point only in inline-snapshot.test.ts, I cannot debug other tests. And I do not understand what makes the conf works for this one, and not for the other ones

**Comment by Brooooooklyn** [comment]
Seem like `sourcemap` is correctly been set, but there are bugs in sourcemap generated.

**Comment by AlexandreDecollas** [comment]
yep, and the breakpoint that works only works because there is no typescript in the test file... These bugs are from the original project, so Do you think I should ask them?

**Comment by Brooooooklyn** [comment]
@kdy1

**Comment by kdy1** [comment]
Can you try https://swc.rs/docs/configuring-swc#inlinesourcescontent?

**Comment by Brooooooklyn** [comment]
@AlexandreDecollas you can try [`swc-jest`](https://www.npmjs.com/package/@swc/jest) with https://swc.rs/docs/configuring-swc#inlinesourcescontent

This project is aim to provide `tsconfig` compatible ability to swc, and https://swc.rs/docs/configuring-swc#inlinesourcescontent is not covered now.

**Comment by AlexandreDecollas** [comment]
thank you, I tried, but nothing seem to work. Maybe I should wait for a fix, or maybe do you know a previous version that worked with sourcemaps?

**Comment by AlexandreDecollas** [comment]
Hi again! 

I investigated a bit, and it seems that actually the sourcemaps are well generated. I modified your transormation process and put some logs to see what happens, and what I saw :
 
* First, we need to modify the unit test before each run, because else, it's not reusing the transform option.

* Secondly, I can see that once the transformed is done with swc-core, the option sourceMap actually work, mean that when true, the sourcemaps are generated, not when false. 

At the end, I have not so much ideas because,  whereas the sourcemaps are generated, the breakpoints still doesn't work.

@kdy1 I tried your option and I also tried swc-jest, it fails the same.

Maybe a last clue is that when I try to debug a dumb test like this : 
```typescript
describe('App', () => {
  it("should be ok!", () => {
    console.log(new Date())
    expect(true).toBeTruthy();
  });
});
```

... and I put a console.log just before sending the transform result, I have this result, containing sourceMaps. I'm wondering this sourcemaps are valid or not : 

```typescript
{
  code: "describe('App', function() {\n" +
    '    it("should be ok!", function() {\n' +
    '        console.log(new Date());\n' +
    '        expect(true).toBeTruthy();\n' +
    '    });\n' +
    '});\n',
  map: '{"version":3,"sources":["<anon>"],"names":["describe","it","console","log","Date","expect","toBeTruthy"],"mappings":"AAAA,QAAQ,CAAC,CAAK,MAAE,QAChB,GADsB,CAAC;IACrB,EAAE,CAAC,CAAe,gBAAE,QACtB,GAD4B,CAAC;QACzB,OAAO,CAAC,GAAG,CAAC,GAAG,CAAC,IAAI;QACpB,MAAM,CAAC,IAAI,EAAE,UAAU;IACzB,CAAC;AACH,CAAC"}'
}
```

Seeing that, do you see something weird? (the mappings seem very unusual to me...)

**Comment by maschwenk** [comment]
@AlexandreDecollas did you ever figure this out? Having the same issue

**Comment by AlexandreDecollas** [comment]
@maschwenk nope, sadly not at this day. If finally you have a solution, feel free to tell me :)

**Comment by kdy1** [comment]
Can you try inlined sourcemap again with newer version of `@swc/core`?

**Comment by maschwenk** [comment]
@kdy1 just to be clear that'd be:

```
{
  "sourceMaps": 'inline',
  "inlineSourcesContent": true
}
```
?

(or the equivalent that `swc-node` configuration?)

Also when you say `newer` do you mean `swc-node` or `@swc/core`? It would be easier for me to test `swc-node` because it has the pre-baked configuration

**Comment by Brooooooklyn** [comment]
@swc-node/* has `swc` configuration for the orignal swc config: https://github.com/Brooooooklyn/swc-node/blob/master/packages/core/index.ts#L27

BTW, I'll make `inlined sourcemap` enabled in `@swc-node/jest` by default in the next release.

**Comment by Brooooooklyn** [comment]
@AlexandreDecollas hey `inlineSourcesContent` is enabled by default in the latest version, could you checkout if this issue is fixed?

**Comment by AlexandreDecollas** [comment]
@Brooooooklyn hey! 

yes, I tested by default with the v1.4.1, and by default breakpoints are not working. but by adding such a conf : 

```
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc-node/jest',
      {
        experimentalDecorators: true,
        swc: {
          sourceMaps: 'inline',
        },
      },
    ],
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './src',
  testRegex: '.spec.(t|j)s$',
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
```

This way, I have the breakpoints working well. So thank you very much for your help! :)

I think btw it could be interesting to add this option by default too (and not only `inlineSourcesContent`), because it's quite often that we have a need for debugging in the UTs

**Comment by Brooooooklyn** [comment]
> I think btw it could be interesting to add this option by default too (and not only inlineSourcesContent), because it's quite often that we have a need for debugging in the UTs

Sure, I'll add it in the next release

**Comment by AlexandreDecollas** [comment]
Thanks, I'm sure that this project will really help the daily work for a lot of people 👍
