### ISSUE TITLE
Wrong this argument in optional call method

### ISSUE THREAD

**Issue by luxueyan** [Brooooooklyn/swc-node#62]
I use a optional call. It throw error.
```
TypeError: Illegal invocation

       95 |   // Remove the old try catch block since there will be no error to be thrown
       96 |   // console.log(element.focus)
    >  97 |   element.focus?.()
          | ^
       98 |   // let _a
       99 |   // (_a = element.focus) === null || _a === void 0 ? void 0 : _a.call(element)
      100 |   Utils.IgnoreUtilFocusChanges = false

      at Function.focus (node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:114:15)
      at attemptFocus (packages/utils/aria.ts:97:1)
      at Object.focusFirstDescendant (packages/utils/aria.ts:159:1)
      at Object.focusFirstDescendant (packages/utils/aria.ts:159:1)
      at packages/drawer/src/index.vue:147:1
```
It looks like the focus method  missed right context. The transformed code may be different with the below 'es5' statement which is transformed by tsc.
```
var _a
(_a = element.focus) === null || _a === void 0 ? void 0 : _a.call(element)
`

**Comment by Brooooooklyn** [comment]
Seems the output code is the same with `babel`, note: the `swc` was implemented followed the babel.

https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYG2FtgOwFwOgGYHsDGBXAzgfjgCgJRA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.11.1&externalPlugins=

**Comment by Brooooooklyn** [comment]
BTW, I have tested in local with codes:
```ts
import test from 'ava'

test('optional function call', (t) => {
  const obj: { method?: () => void } = {}
  t.notThrows(() => obj.method?.())
})
```

Seems to be no problem.

**Comment by luxueyan** [comment]
I run transformSync('a.focus?.()', 'test2.js'), the transformed code is 
```js
"use strict";
var ref;
(ref = a.focus) === null || ref === void 0 ? void 0 : ref.call(ref);
```
`ref.call(ref)` was not right. The expected code is `ref.all(a)`

**Comment by Brooooooklyn** [comment]
@kdy1

**Comment by kdy1** [comment]
Thanks for the report!
I'll fix it soon.

**Comment by Brooooooklyn** [comment]
Close via https://github.com/Brooooooklyn/swc-node/commit/5d9966f9eb4b1026356a3f824568f9804faa05ff
