### ISSUE TITLE
How do I run this from the CLI?

### ISSUE THREAD

**Issue by jameshfisher** [Brooooooklyn/swc-node#638]
Sorry if this is a stupid question, but I'm looking to do something like:

```
$ echo 'console.log("hello")' > foo.ts
$ npx @swc-node/core foo.ts
npm ERR! could not determine executable to run
```

I've looked and it seems like the package doesn't include an executable at all. I'm expecting an executable because it advertises itself as an alternative to `ts-node`.

**Comment by Brooooooklyn** [comment]
node -r @swc-node/register index.ts

See https://github.com/Brooooooklyn/swc-node/tree/master/packages/register

**Comment by jameshfisher** [comment]
Oh perfect, thanks! 🚀

(I suggest putting this at the top of the https://github.com/Brooooooklyn/swc-node README, since I expect most people are finding this project as an alternative to ts-node)

**Comment by hairyf** [comment]
You can use https://github.com/hairyf/swrun
