### ISSUE TITLE
Cannot set object keys from const

### ISSUE THREAD

**Issue by moltar** [Brooooooklyn/swc-node#64]
After the last update, I have a pretty odd failure, which I cannot repro on a smaller codebase.

Essentially, I am importing a const that defines a key of the object.

```ts
import {
  ADVERTISING_AUTHORIZATION_CREDENTIALS,
  ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI,
} from '../../infra/constants'
```

Then, I am using it to construct an object:

```ts
    console.log(
      'ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI',
      ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI,
    )

    const enviro = {
      [ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI]: 'http://example.com',
    }
    console.log('enviro', enviro)
```

This produces the following output:

```
  console.log
    ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI

      at Object.<anonymous> (...test.ts:39:1)

  console.log
    enviro { undefined: 'http://example.com' }

      at Object.<anonymous> (...test.ts:47:1)
```

Notice that `ADVERTISING_AUTHORIZATION_REDIRECT_FINAL_URI` does have a value, as evident from the first console log.

Yet when using in the context of object key, it seems to be `undefined`.

Any tips on how to repro this better are appreciated!

Cheers!

**Comment by Brooooooklyn** [comment]
First, try to run jest with `--no-cache` flag: `npx jest --config ./jest.config.js --no-cache PATH_TO_ERROR_SPEC`
If the error still appear, try to log the transformed file while running the test:

1. enter the `@swc-node/jest` dist file in `node_modules/@swc-node/jest/lib/index.js`
2. Add log to source file:

```diff
- return core_1.transformJest(src, path, transformOptions);
+ const { code, map } core_1.transformJest(src, path, transformOptions);
+ console.log(code)
+ return { code, map }
```

3. Record the log:

```bash
npx jest ./PATH_TO_JEST_CONFIG --no-cache ./PATH_TO_SPEC_FILE > log.js
```

**Comment by moltar** [comment]
Seems to be resolved now... Never got around to actually digging into it. But after upgrading to latest, the issue is gone. I'll close this for now. Thanks!
