### ISSUE TITLE
(Maybe) Merge back into swc?

### ISSUE THREAD

**Issue by kdy1** [Brooooooklyn/swc-node#68]
I'm not sure about this, but it provides almost identical api to `@swc/core`

**Comment by Brooooooklyn** [comment]
I will use @swc/core directly after add `linux-musl` support to @swc/core

**Comment by kdy1** [comment]
Great, I'll add support for it after making the parser faster. 
I expect parser to be 2 ~ 4 times faster after it.

**Comment by kdy1** [comment]
Now official swc supports linux-musl and has jest support

**Comment by Brooooooklyn** [comment]
> I will use @swc/core directly after add linux-musl support to @swc/core

I will do it tomorrow
