### ISSUE TITLE
结合enzyme使用报错

### ISSUE THREAD

**Issue by 729993031** [Brooooooklyn/swc-node#9]
![44C52EA0-CD83-489a-A2DE-C4D3F85B2D0D](https://user-images.githubusercontent.com/13050361/89243215-00e7f100-d636-11ea-8279-7a76fe530f0f.png)
![184B4014-B00A-4b8f-ACB0-6BF2BCF2B88F](https://user-images.githubusercontent.com/13050361/89243220-02191e00-d636-11ea-8271-febf10d88fa2.png)

**Comment by 729993031** [comment]
![551058E6-3E10-4a1d-A556-03E9B2EF7608](https://user-images.githubusercontent.com/13050361/89243387-65a34b80-d636-11ea-859c-ae708daf1eed.png)

**Comment by Brooooooklyn** [comment]
试着改一下配置:

```js
transform: {
  '^.+\\.(t|j)sx?$': ['@swc-node/jest', {
    tsx: true,
  }]
}

```

记得使用目前最新的版本，老版本可能会有问题
